# 应用名
spring:
  application:
    name: spring-ai-mcp-server
  profiles:
    active: docker # 指定生效的环境配置
  mail:
    host: smtp.163.com               # 邮箱host
    port: 465                      # 邮箱固定端口
    protocol: smtp                  # 邮箱协议
    default-encoding: UTF-8         # 默认编码
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

# MyBatisPlus 的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
  mapper-locations: classpath*:/mappers/*.xml

# 日志级别
logging:
  level:
    root: info