# 端口号
server:
  port: 8080

spring:
  ai:
    openai:
      base-url: ${OPEN_AI_BASE_URL}
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: ${OPEN_AI_MODEL}
        completions-path: ${OPEN_AI_COMPLETIONS_PATH}
