# 端口号
server:
  port: 8080

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: '你的密码'
  ai:
    openai:
      base-url: ${OPEN_AI_BASE_URL}
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: ${OPEN_AI_MODEL}
    vectorstore:
      redis:
        initialize-schema: true         # 是否初始化所需的模式
        index-name: ljx-vectorstore     # 用于存储向量的索引名称
        prefix: 'embedding:'            # Redis 键的前缀
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client-1.0.0
        type: ASYNC
        streamable-http:
          connections:
            gdMap:
              url: https://mcp.amap.com
              sse-endpoint: /mcp?key='高德地图key'
        sse:
          connections:
            dateTool:
              url: http://localhost:9090
              sse-endpoint: /sse
        stdio:
          servers-configuration: classpath:mcp-server.json

cors:
  domain: http://127.0.0.1:5501/